### ISSUE TITLE
Crash when installing/uninstalling a driver

### ISSUE THREAD

**Issue by davkean** [davkean/audio-switcher#24]
Reinstalled the desktop camera drivers on my machine and audio switcher crashed with the following:

System.NotImplementedException: PropVariant VT_EMPTY
   at AudioSwitcher.Audio.Interop.PropVariant.get_Value()
   at AudioSwitcher.Audio.PropertyStoreProperty.get_Value()
   at AudioSwitcher.Audio.PropertyStore.TryGetValue(PropertyKey key, Object& value)
   at AudioSwitcher.Audio.AudioDevice.get_DeviceFriendlyName()
   at AudioSwitcher.UI.ViewModels.AudioDeviceViewModel.UpdateStatus(AudioDeviceManager deviceManager)
   at AudioSwitcher.UI.ViewModels.AudioDeviceViewModelManager.OnDefaultDeviceChanged(Object sender, DefaultAudioDeviceEventArgs e)
   at AudioSwitcher.Audio.AudioDeviceManager.<>c__DisplayClassa.<AudioSwitcher.Audio.Interop.IMMNotificationClient.OnDefaultDeviceChanged>b__9()
   at AudioSwitcher.Audio.AudioDeviceManager.<>c__DisplayClass11.<InvokeOnSynchronizationContext>b__f(Object state)

**Comment by davkean** [comment]
Also this left a device in the device menu:

![image](https://cloud.githubusercontent.com/assets/1103906/6100705/823f2a6e-afc9-11e4-8c45-58d2d9022e18.png)
