### ISSUE TITLE
Suepend and resume caused this

### ISSUE THREAD

**Issue by SimonCropp** [davkean/audio-switcher#33]
Might be because i plugged in an external mic and speaker before resuming

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at AudioSwitcher.Audio.AudioDeviceManager.GetDefaultAudioDevice(AudioDeviceKind kind, AudioDeviceRole role) in c:\Code\audio-switcher\src\AudioSwitcher\Audio\AudioDeviceManager.cs:line 124
   at AudioSwitcher.Audio.AudioDeviceManager.IsDefaultAudioDevice(AudioDevice device, AudioDeviceRole role) in c:\Code\audio-switcher\src\AudioSwitcher\Audio\AudioDeviceManager.cs:line 107
   at AudioSwitcher.UI.ViewModels.AudioDeviceViewModel.CalculateDeviceDefaultState(AudioDeviceManager deviceManager) in c:\Code\audio-switcher\src\AudioSwitcher\UI\ViewModels\AudioDeviceViewModel.cs:line 254
   at AudioSwitcher.UI.ViewModels.AudioDeviceViewModel.UpdateStatus(AudioDeviceManager deviceManager) in c:\Code\audio-switcher\src\AudioSwitcher\UI\ViewModels\AudioDeviceViewModel.cs:line 79
   at AudioSwitcher.UI.ViewModels.AudioDeviceViewModelManager.OnDeviceStateChanged(Object sender, AudioDeviceStateEventArgs e) in c:\Code\audio-switcher\src\AudioSwitcher\UI\ViewModels\AudioDeviceViewModelManager.cs:line 99
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at AudioSwitcher.Audio.AudioDeviceManager.<>c__DisplayClass1.<AudioSwitcher.Audio.Interop.IMMNotificationClient.OnDeviceStateChanged>b__0() in c:\Code\audio-switcher\src\AudioSwitcher\Audio\AudioDeviceManager.cs:line 154
   at AudioSwitcher.Audio.AudioDeviceManager.<>c__DisplayClass11.<InvokeOnSynchronizationContext>b__f(Object state) in c:\Code\audio-switcher\src\AudioSwitcher\Audio\AudioDeviceManager.cs:line 234


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AudioSwitcher
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Code/audio-switcher/src/AudioSwitcher/bin/Debug/AudioSwitcher.exe
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MetadataViewProxies_c6889f80-f9ce-42c8-9425-72cf6f9abeef
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.57.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by davkean** [comment]
Thanks will look at tightening this. Was the speaker USB?

**Comment by SimonCropp** [comment]
yeah. USB combine mic and speaker
