### ISSUE TITLE
Crashes on Windows 10 build 10122

### ISSUE THREAD

**Issue by GeorgeHahn** [davkean/audio-switcher#34]
Same as before - crashes when setting a new default audio device. Let me know if there's anything else I can provide.

![6ani7pl 1](https://cloud.githubusercontent.com/assets/502747/7755889/741d610c-ffc5-11e4-92da-770a112f1920.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast COM object of type 'AudioSwitcher.Audio.Interop.PolicyConfig' to interface type 'AudioSwitcher.Audio.Interop.IPolicyConfig3'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{8F9FB2AA-1C0B-4D54-B6BB-B2F2A10CE03C}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at AudioSwitcher.Audio.AudioDeviceManager.SetDefaultAudioDevice(AudioDevice device, AudioDeviceRole role) in c:\Users\George\Documents\GitHub\audio-switcher\src\AudioSwitcher\Audio\AudioDeviceManager.cs:line 95
   at AudioSwitcher.Audio.AudioDeviceManager.SetDefaultAudioDevice(AudioDevice device) in c:\Users\George\Documents\GitHub\audio-switcher\src\AudioSwitcher\Audio\AudioDeviceManager.cs:line 71
   at AudioSwitcher.UI.Commands.AudioDeviceCommand.Run(AudioDeviceViewModel argument) in c:\Users\George\Documents\GitHub\audio-switcher\src\AudioSwitcher\UI\Commands\AudioDeviceCommand.cs:line 28
   at AudioSwitcher.Presentation.CommandModel.Command`1.AudioSwitcher.Presentation.CommandModel.ICommand.Run(Object argument) in c:\Users\George\Documents\GitHub\audio-switcher\src\AudioSwitcher\Presentation\CommandModel\CommandOfT.cs:line 44
   at AudioSwitcher.Presentation.UI.ToolStripItemCommandBinding.OnItemClicked(Object sender, ToolStripItemClickedEventArgs e) in c:\Users\George\Documents\GitHub\audio-switcher\src\AudioSwitcher\Presentation\UI\ToolStripItemCommandBinding.cs:line 85
   at System.Windows.Forms.ToolStripItemClickedEventHandler.Invoke(Object sender, ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnItemClicked(ToolStripItemClickedEventArgs e)
   at AudioSwitcher.Presentation.UI.AudioContextMenuStrip.OnItemClicked(ToolStripItemClickedEventArgs e) in c:\Users\George\Documents\GitHub\audio-switcher\src\AudioSwitcher\Presentation\UI\AudioContextMenuStrip.cs:line 72
   at AudioSwitcher.Presentation.UI.Views.DeviceFlyoutView.OnItemClicked(ToolStripItemClickedEventArgs e) in c:\Users\George\Documents\GitHub\audio-switcher\src\AudioSwitcher\UI\Views\DeviceFlyoutView.cs:line 54
   at System.Windows.Forms.ToolStrip.HandleItemClick(ToolStripItem dismissingItem)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at AudioSwitcher.Presentation.UI.Views.DeviceFlyoutView.OnMouseUp(MouseEventArgs e) in c:\Users\George\Documents\GitHub\audio-switcher\src\AudioSwitcher\UI\Views\DeviceFlyoutView.cs:line 43
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at AudioSwitcher.Presentation.UI.Views.DeviceFlyoutView.WndProc(Message& m) in c:\Users\George\Documents\GitHub\audio-switcher\src\AudioSwitcher\UI\Views\DeviceFlyoutView.cs:line 82
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.73.0 built by: NETFXREL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AudioSwitcher
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Users/George/Documents/GitHub/audio-switcher/src/AudioSwitcher/bin/Debug/AudioSwitcher.exe
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.73.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.73.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.73.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.73.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.73.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.73.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.73.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MetadataViewProxies_959aa4f6-7bca-45df-b99c-f82502f033ee
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.73.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.73.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Ventajou** [comment]
Getting the same error on 10159

**Comment by davkean** [comment]
It looks like this GUID on IPolicyConfig3, needs to be now ca286fc3-91fd-42c3-8e9b-caafa66242e3.

**Comment by Ventajou** [comment]
Yes, I just tried and that new GUID works, thanks!

**Comment by davkean** [comment]
Fixed this.

**Comment by irzyxa** [comment]
Doesn't work on Windows 10 build 10532, seems windows changed guid again
